apiVersion: v1
kind: ConfigMap
metadata:
  name: entities-job-config
  namespace: dmr
data:
  database.service: "entities-psql:5432"
  database.user: "entities"
  database.password: "s0m3R4nd0mp4ssw0rd"
  database.name: "entities"
